apiVersion: v1
kind: Service
metadata:
  name: simple-node-server-lb
  namespace: default
spec:
  ports:
  - name: http
    port: 5000
    targetPort: 80
  selector:
    webserver: simple-node-server
  sessionAffinity: None
  type: LoadBalancer
